sudo: required

language: csharp

cache:
  directories:
    - $HOME/cache

services:
  - docker

script:
  - docker build -t webapp:test -f ./dockerfile/test .
  - docker run -it --rm -v $PWD/publish:/root/publish -v $PWD/packages:/root/.nuget/packages webapp:test